hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_preformer
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working directory unchanged
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.trained_model_path
          - EVAL.trained_model_path
          - mode
          - output_dir
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 1024
output_dir: ${hydra:run.dir}
log_freq: 20

# set training hyper-parameters
SQ_LEN: 6
IMG_H: 192
IMG_W: 256
USE_SAMPLED_DATA: false

# set train data path
TRAIN_FILE_PATH: /patch/to/ERA5/
DATA_MEAN_PATH: examples/weather/datasets/era5/stat/mean.nc
DATA_STD_PATH: examples/weather/datasets/era5/stat/std.nc

# set evaluate data path
VALID_FILE_PATH: /patch/to/ERA5/

# model settings
MODEL:
  afno:
    input_keys: ["input"]
    output_keys: ["output"]
    shape_in: [6, 12, IMG_H, IMG_W]

# training settings
TRAIN:
  epochs: 150
  save_freq: 20
  eval_during_train: true
  eval_freq: 20
  lr_scheduler:
    epochs: ${TRAIN.epochs}
    learning_rate: 0.001
    by_epoch: true
  batch_size: 16
  pretrained_model_path: null
  checkpoint_path: null

# evaluation settings
EVAL:
  pretrained_model_path: null
  compute_metric_by_batch: true
  eval_with_no_grad: true
  batch_size: 16
